name: flutter_post_build
description: A command-line tool to rename and organize Flutter build artifacts after the build process is complete.
version: 1.1.1
homepage: https://bxamra.github.io/
repository: https://github.com/BXAMRA/flutter_post_build
issue_tracker: https://github.com/bxamra/flutter_post_build/issues
license: MIT

environment:
  sdk: ">=3.0.0 <4.0.0"

# Defines the command-line executable available after global activation
executables:
  flutter_post_build: flutter_post_build

dependencies:
  path: ^1.9.0
  yaml: ^3.1.2
  args: ^2.4.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
